import heroImg from "../assets/KARLO Header Image.webp";
import turtleShell from "../assets/turtle+shell.webp";

import "./styling/read.css";

import Footer from "../components/footer/footer";
import HeroImage from "../components/heroImage/heroImage";
import CreditFooter from "../components/creditFooter/creditFooter";
import TextBox from "../components/textBox/textBox";
import SectionTitle from "../components/sectionTitle/sectionTitle";
import PoemBox from "../components/poemBox/poemBox";

import ReadContent from "../components/readContent/readContent";


function Read() {
  return (
    <div>
      <HeroImage src={heroImg} alt="Karlo Mila Hero" />
      <CreditFooter text="Artist credit: Huriana Kopeke-Te Ao" />
        
        
        <div className="read-page">
        <SectionTitle title="Read" />    
      <div className="read-content">
      <TextBox paragraphs={[
        "Kia ora, Mālō e lelei and welcome to this little reading perch that I've put together. I have gathered bits and pieces that will link you to some of my poems and writing."
      ]} />

      <TextBox paragraphs={[
        "It makes sense to begin with Eating Dark Chocolate and Watching Paul Holmes' Apology as this is the first poem of mine that was ever published. It was written in response to a racist rant made by a well-known broadcaster in Aotearoa / New Zealand. I sent this poem to my creative writing teacher Maualaivao Albert Wendt when I was a student. He emailed it out to his friends and colleagues and it went a bit 'viral'. I heard via word of mouth, that the Editor of the Listener had asked if his magazine could publish it. I had no idea how to submit work to be published at the time. I recall cutting and pasting the poem into a feedback form on the Listener Website.",
        "Maualaivao Albert continued to be influential in my writing career. Even though I was a new writer, he included Wednesday Afternoon in the Whetu Moana Anthology. This poem was chosen as one of the \"Ōrongohau Best New Zealand Poems\". This was one of my first \"big breaks\". I was a huge fan of Albert Wendt's writing and he had a direct influence on my poetry. Acknowledging my literary whakapapa, artistic elders and writing 'older siblings' is a repeated practice in my books. I have been inspired by so many Pacific, Māori and writers of colour in my journey. Their voices have created space and helped enable mine, so acknowledgement and odes to elders feel important to me.",
        "After I completed his creative writing paper, Maualaivao Albert suggested to Huia Publishers that they look at my work. They went on to publish Dream Fish Floating which won the Jessie MacKay Best First Book of Poetry Award in 2006. This changed my life forever. Again, one of the poems from that book Sacred Pulu was selected for Ōrangohau. Re-reading this poem now, it feels so true to my experience of being a young Pasifika person, living in Tāmaki Makaurau and trying to figure myself out."
      ]} />

      <TextBox paragraphs={[
        "This \"trying to figure out\" what it meant to be Pasifika in Aotearoa led to a PhD in the area. Being of Tongan heritage is very important to me and writing about Tonga, such as this Ode to Princess Ashika has been a defining part of my creative journey. My second book, \"A Well Written Body\" focused a lot on Tonga and the politics and poetics of place.",
        "I have always written across multiple mediums and this included, for a while, writing an Op-Ed called 'Pacific Current' for the Dominion-Post. I stopped after a while, particularly after I started to receive disturbing mail at my home from racists. Occasionally, when I feel stirred, I'll still write an Op-Ed. I have always been a political writer, and speaking unafraid into the silence has been a hallmark of my writing."
      ]} />

      <TextBox paragraphs={[
        "However, as an antidote to Op-Eds and the ugliness of daily political life in Aotearoa, I buried myself deep in Pacific mythology and ancient archetype. This was also an antidote to writing about contemporary challenges faced by Pacific peoples and the inequalities they experience in an empirical, scholarly and sociological way. Diving deep into ancestral genius felt like one of the most empowering things I could do.",
        "My postdoctoral research into indigenous knowledge from the Pacific took me somewhere deeply mythical, metaphorical, language-based, proverbial, poetic, and narrative-oriented. It profoundly changed me. Through this five year research process I developed Mana Moana and a framework that was indigenous. It informs the curriculum of two leadership programmes at Leadership New Zealand.",
        "This research changed the nature of my poetry forever. Meditating on concepts widely shared among the islands of the Pacific, such as Mana, became a full time focus. The influence of Mana Moana is also evident in my writing in essay form, as well as academic works. It is very obvious the way philosophy and understandings indigenous to the Moana have impacted upon my poetry. You can see this in the Mana Moana Meditation that I created with Michael Tuffery. To view this multidisciplinary work, enter via karanga through a portal that leads to the digital ocean, click on the blue stingray and listen. It remains one of the artworks I am most proud of."
      ]} />

      <TextBox paragraphs={[
        "During Covid-19, I came to write a number of meditations and this is something I have continued to do. It seemed to be a way that poetry could serve our collective wellbeing during a difficult time. I wrote personally and poetically about the impact of Covid-19. It was a time when we were all grateful for art.",
        "Potentially my own blend of activism, belief in the value of indigenous knowledge, and willingness to speak back to power, comes together in this Poem for the Commonwealth. I read this at the Commonwealth Heads of Government Peoples' Forum, after Bill Gates and Prime Minister of England spoke. This remains a career highlight, but the most special thing I have ever done is read a poem at Moana Jackson's tangi. This has been my greatest honour. I continue to write poetry regularly, and some of my new poems can be found below."
      ]} />

      <TextBox paragraphs={[
        "I hope you enjoyed that journey through a wide variety of examples of my writing.",
        "Ngā Mihi,",
        "Karlo"
      ]} />
      </div>


        </div>

        <ReadContent
  entries={[
    {
      title: "The Distiller's Guide to Poetry",
      collection: "For G",
      imageSrc: turtleShell,
      imageAlt: "Turtle shell",
      imageCredit: "Photo credit: Raymond Sagapolutele",
      lines: [
        "1.",
        "",
        "My friend has a brain injury.",
        "",
        "Concussed,",
        "",
        "he sends me poetry.",
        "",
        "My own.",
        "",
        "It was meant for someone else,",
        "",
        "but I drink in the words",
        "as if I am a stranger to them.",
        "",
        "I swill them around in my mouth,",
        "as if I am discerning -",
        "swirling something",
        "familiar, fragrant,",
        "on my tongue.",
        "",
        "Yes,",
        "Spirits, neat,",
        "on the rocks",
        "",
        "Medicinal words",
        "quenching a strange thirst,",
        "in the middle",
        "of a hot pandemic.",
        "",
        "2.",
        "",
        "Yes,",
        "those words wrote my knowing",
        "when I didn't even know",
        "what I was talking about.",
        "",
        "Poet.",
        "Don't know it.",
        "You know how it goes.",
        "",
        "3.",
        "",
        "I voice record myself back to my friend,",
        "saying:",
        "",
        "I love that poetry can still be something whole",
        "for you,",
        "in the broken",
        "of brain injury.",
        "",
        "(TBH I said it better in these lines",
        "than out loud in real life",
        "and that's one of the gifts of poetry!)",
        "",
        "Oh poetry,",
        "I love you so.",
        "",
        "Wholeness",
        "in smallness.",
        "Best words in",
        "Best order.",
        "Fewest words",
        "Greatest meaning.",
        "",
        "You know how",
        "clumsily",
        "we mouth you",
        "back to yourself.",
        "",
        "Light.",
        "Gift.",
        "",
        "4.",
        "",
        "I am a poet with a PhD,",
        "And I am not a big fan",
        "of dissertations.",
        "I cannot recommend them.",
        "Poetry, however.",
        "",
        "Give me the key-words",
        "that unlock",
        "the open mouth of",
        "a fast-talking over-dressed beast",
        "spending all it's time",
        "quoting everybody else.",
        "",
        "I want to skip the intro,",
        "bypass the methodology section,",
        "Take me straight",
        "to the four original lines of this thesis.",
        "",
        "Give me",
        "the findings",
        "of the findings.",
        "",
        "Give me the abstract",
        "of the abstract.",
        "",
        "Whisper it to me,",
        "like they are hot uncomfortable secrets",
        "you spent three years seeking.",
        "",
        "That's poetry.",
        "",
        "References are always best left",
        "as mysteries.",
        "",
        "Researcher,",
        "give me the",
        "elevator pitch you'd give straight to God,",
        "if you encountered her",
        "policy-making",
        "somewhere small and square.",
        "",
        "Condense it into the",
        "concise summary",
        "of prayer,",
        "uplifting.",
        "",
        "5.",
        "",
        "No. I don't even have time for the movie",
        "moving frame by frame,",
        "minute by minute:",
        "take me straight to that moment -",
        "one hour and 17 minutes in -",
        "",
        "where in the silence",
        "sitting twinned",
        "on that bench",
        "on that hard-to-reach beach,",
        "you realise",
        "you are sitting-too-close-to-each-other",
        "and far-too-faraway",
        "from everything else.",
        "",
        "That moment when he pulls out his phone",
        "to show you,",
        "on the small cracked screen -",
        "your location on google earth -",
        "chewing up his precious data",
        "his arm warm against your body.",
        "",
        "That moment he shows you,",
        "how you are right at the ihu",
        "of the isthmus –",
        "\"See here – the nose\" -",
        "and you peer into",
        "the small shattered glass",
        "of that tiny birds-eye view",
        "in his hand.",
        "",
        "You look down",
        "to look up",
        "at the google green and earth blue.",
        "",
        "And you know you've seen -",
        "exactly what you already knew",
        "amidst all his rapidly declining data.",
        "",
        "You know",
        "with satellite surety",
        "you are",
        "exactly where",
        "you want to be",
        "and no other where",
        "could be anywhere",
        "as lovely.",
        "",
        "Located.",
        "With accuracy",
        "and precision.",
        "",
        "Yes, just take me straight there -",
        "to that hard-to-reach beach",
        "off-the-track at Ihumātao.",
        "Long before the tents came.",
        "",
        "When you suddenly knew",
        "exactly where you both were,",
        "in the universe,",
        "unfolding.",
        "",
        "6.",
        "",
        "I want to taste it",
        "the day after.",
        "",
        "All that was tip of your tongue.",
        "All that was choked in your throat.",
        "",
        "That growing and knowing between us,",
        "ripening until we fell.",
        "",
        "That forbidden fruit",
        "we hid behind our backs.",
        "",
        "I want to bite from its flesh:",
        "every pip, seed, segment",
        "taste it on my tongue.",
        "",
        "Everything worth remembering.",
        "Everything worth writing down.",
        "",
        "Juiced. Pulped. Pureed. Dried.",
        "Extracted.",
        "",
        "Elegantly spooned",
        "back to us",
        "as essence.",
        "",
        "Tonic.",
        "Medicine.",
        "Poetry.",
        "",
        "7.",
        "",
        "I want to taste it",
        "years later.",
        "",
        "After it has",
        "steeped,",
        "and been spread",
        "on malting floors.",
        "",
        "Ground into grist.",
        "Mashed. Mixed.",
        "",
        "Long after the living has fed on the sugars.",
        "Fermenting. Yes, the violent froth.",
        "",
        "Then it all dies down,",
        "to come-out-in-the-wash.",
        "",
        "I know",
        "the shape of the pot",
        "matters more than you'd think -",
        "The stillness",
        "distinctive.",
        "",
        "Until all the vapours",
        "condense",
        "into liquid,",
        "that",
        "condensed",
        "smooth running",
        "syrup,",
        "complex",
        "full-bodied:",
        "life's leftovers –",
        "prized, preserved,",
        "thick",
        "treacle.",
        "",
        "Poetry demands",
        "further distillation.",
        "",
        "Washed. Refined.",
        "Lying as low wines,",
        "until only the heart of the run",
        "remains. Pure centre cut.",
        "",
        "This then passes",
        "through the spirit safe,",
        "to emerge colourless,",
        "fiery, flammable",
        "intoxicating",
        "spirits.",
        "",
        "Worthy",
        "of life's",
        "last sip.",
        "",
        "8.",
        "",
        "Once you've seen the ihu",
        "you can never unsee",
        "the way",
        "something that you can't see",
        "is inhaling everything in",
        "all the time.",
        "",
        "Spirits.",
        "",
        "Can you sense the lingering",
        "fragrance of that moment?",
        "Through the splintered glass",
        "of how I remember it?",
        "",
        "Such a small screen.",
        "",
        "With this broken birds-eye view",
        "I offer you",
        "my clarity:",
        "googling earth memories,",
        "laying them down to rest.",
        "to steep. purify. refine.",
        "",
        "Yes, I make them mine.",
        "My own distinctive stills.",
        "So still inside me.",
        "",
        "And when I am thirsty,",
        "I will drink.",
        "",
        "And when you are parched,",
        "I will offer you my glass.",
        "",
        "I offer you my clarity.",
        "",
        "An elixer",
        "aged, brewed and",
        "mixed from memories,",
        "meaning, moments:",
        "medicinal.",
        "",
        "So all that is too big",
        "can be reduced to small.",
        "",
        "So that a lifetime can be distilled",
        "into four original lines.",
        "",
        "So that all that is too broken,",
        "can return to a single rhyme,",
        "and be enough,",
        "be.enough.",
        "",
        "I write these words",
        "so that all the unspoken",
        "can speak",
        "like spirits.",
        "",
        "All of it held,",
        "in the palm of poetry's hand,",
        "where",
        "all is",
        "eventually",
        "understood,",
        "and",
        "absolved.",
      ],
    },
    
      {
  title: "Travelling",
  collection: "For Delicia, with reference to Rumi and his poem The Wagon",
  imageSrc: null,
  lines: [
    "Here we are,",
    "in the digital age",
    "experiencing connectivity",
    "at the highest speeds;",
    "isolated in ways",
    "we have never been before.",
    "",
    "Covid. The technology",
    "of touch -",
    "without touching.",
    "",
    "We are still",
    "hard-wired",
    "for connection.",
    "",
    "My finger",
    "forever,",
    "on the",
    "pulsating.",
    "",
    "I feel you",
    "through the screen.",
    "",
    "Our thoughts have always travelled",
    "beyond our minds, unspoken and",
    "angled on face –",
    "shaped in the language of body.",
    "Kinetic. Energetic. Frenetic.",
    "Carried in the",
    "tele-phone of tone:",
    "open-mouthed, audio, radio, aural.",
    "",
    "Our feelings have always travelled across time and space",
    "landing in the bedrooms of beloveds,",
    "before texts and sexts, DMs and PMs,",
    "where they waited, open-hearted,",
    "to receive us.",
    "",
    "Electro-magnetic.",
    "Morse code murmurs of heart-beat – tap-tapping",
    "the lag, the latency -",
    "breakthrough of throughput.",
    "The broadening of our bandwidth -",
    "everything we can",
    "and can't possibly",
    "know.",
    "",
    "We have always travelled through nervous systems",
    "into our shared spaces.",
    "Vā - the inter - of everything.",
    "",
    "We are waves",
    "of energy, wayfinding,",
    "in the moving ocean of each other.",
    "",
    "Currents, emotion, light, frequency;",
    "all of us emitting in every interaction.",
    "",
    "Charging each other,",
    "long before",
    "technology expanded us.",
    "",
    "Still so much we don't understand:",
    "such as synchronies",
    "of whale and kauri,",
    "remembered in our underwater bones.",
    "We recall exchanging skin.",
    "The great forgetting.",
    "And yet, here we are, accelerating, faster than 5G",
    "although nobody knows where we are going.",
    "",
    "We hope to find that place,",
    "beyond all binaries",
    "in the algorithm of the ancient,",
    "a spatial field,",
    "entirely energetic,",
    "where virtual",
    "merges with reality.",
    "",
    "I will meet you there.",
    "",
    "For when our souls lie down",
    "in that simulated grass,",
    "this oversubscribed dimension",
    "becomes too over-inscribed",
    "to even type.",
    "",
    "All the language, logic,",
    "predictive text -",
    "even the idea of 'each other'",
    "becomes obsolete.",
    "",
    "We will no longer be the energy of who we are.",
    "",
    "The dancing particles in the air",
    "transmit and receive",
    "these secrets.",
    "",
    "Let us awaken to the signalling.",
    "",
    "Don't go back to sleep.",
    "",
    "Ask",
    "intentionally.",
    "",
    "Attune.",
    "",
    "For here is where",
    "the worlds touch.",
    "",
    "We orbit",
    "ceaselessly around",
    "this unseen altar.",
    "",
    "The portal is a circle.",
    "",
    "Ever-open.",
    "",
    "Don't go back to sleep.",
    "",
    "Here,",
    "we dissolve",
    "beyond separation.",
  ],
},
        
  ]}
/>


      <Footer />
    </div>
  );
}

export default Read;